services:
  db:
    image: postgres:13
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: piscineds
      POSTGRES_USER: macrespo
      POSTGRES_PASSWORD: mysecretpassword
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
